env:
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  no-undef: 0
  array-callback-return: 0
  consistent-return: 0
  default-case: 0