name: Code checks

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.15.0
    - name: Install Dependencies
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.2.0
      env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}